### ISSUE TITLE
Filter results based on the form inputs bellow the map

### ISSUE THREAD

**Issue by JanLikar** [JanLikar/covid#9]

**Comment by cmdctrlesc** [comment]
Working on this now. Currently the db query requires both the minimum date and the maximum date to be selected by the user. Should we make it so that only one is required? If I'm not mistaken that would mean three different cases (only min, only max, both) and a different query for each. What do you think would make more sense from the user's perspective?

**Comment by persho** [comment]
@JanLikar @cmdctrlesc hello Una, good to see you around, its been ages :) 

I noticed that dates filtering does not work, any date you change, all dots disappear.

**Comment by JanLikar** [comment]
@persho I'm sure it should work on the latest staging.

**Comment by JanLikar** [comment]
@persho Ah shit, my bad. Fixing it now.

**Comment by JanLikar** [comment]
Fixed now. Apparently, I forgot how callbacks work :D
